name: quiver
description: >-
  Quiver is a set of utility libraries for Dart that makes using many Dart
  libraries easier and more convenient, or adds additional functionality.
homepage: https://github.com/google/quiver-dart
version: 3.0.0-nullsafety.1
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  matcher: ^0.12.10-nullsafety
  meta: ^1.3.0-nullsafety
dev_dependencies:
  path: ^1.8.0-nullsafety
  test: ^1.16.0-nullsafety
#DDC_TEST:  build_runner: ^1.3.1
#DDC_TEST:  build_test: ^0.10.6
#DDC_TEST:  build_web_compilers: ^2.0.0

# The above dependencies are used for running the dartdevc_test task on Travis.
# Since build_runner indirectly depends on quiver, we patch these in at test
# time to avoid creating a circular dependency.
